### ISSUE TITLE
Add option to prevent accidental deletion of a user pool

### ISSUE THREAD

**Issue by philippta** [lgallard/terraform-aws-cognito-user-pool#53] opened 2021-04-28 11:55 UTC
User pools, like databases are a critical infrastructure resource. Because of that it would be only reasonable to have an option to prevent it from being accidentally destroyed by terraform (and uncautions users).

One way to achieve this would be to add the `prevent_destroy` lifecycle argument to the user pool:
```terraform
resource "aws_cognito_user_pool" "pool" {
  # ...

  lifecycle {
    prevent_destroy = var.prevent_destroy
  }
}
```

It would be great if this module could offer this feature.

**Comment by lgallard** [comment] 2021-04-30 17:23
@philippta I like the idea. I'll include in the next release!

**Comment by lgallard** [comment] 2021-05-21 14:29
This issue was addressed in release 0.11.0!

**Comment by lgallard** [comment] 2021-05-21 20:07
@philippta I had to revert it due to #54. As soon as it fixed in the provider I will include @Waschnick implementation

**Comment by Waschnick** [comment] 2021-05-24 13:07
> @philippta I had to revert it due to #54. As soon as it fixed in the provider I will include @Waschnick implementation

Hey @lgallard sorry if I hadn't tested the changes enough. Your link is not correct, can you tell me what the issue was?

**Comment by lgallard** [comment] 2021-05-24 17:52
@Waschnick I reverted it because there were reports about people unable to do plan/apply because of `prevent_destroy` using a variable. The root cause seem to be reported [here](https://github.com/hashicorp/terraform/issues/22544) in the AWS provider for other resources as well.

You are right, the correct issue where it was reported in this project was #58!

**Comment by AutomationD** [comment] 2022-08-29 15:06
This is a pretty critical issue to us as well. 

@lgallard do you think we could create some special fork/version history that would have it enabled by default statically? Maybe `10.18.2` for the most recent one or maybe you'd be interested to maintain a fork like [terraform-aws-cognito-user-pool](https://github.com/lgallard/terraform-aws-cognito-user-pool-protected)?

**Comment by pb0101** [comment] 2022-10-26 00:34
https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-deletion-protection.html

may be add support for this

**Comment by lgallard** [comment] 2022-10-28 22:53
@pb0101 It seems is not yet implemented in the Terraform provider, or is not documented [here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cognito_user_pool) , and there's a open issued about using variables to handle this [here](https://github.com/hashicorp/terraform/issues/22544).

As soon it implemented in the provider, I'll be more that happy to include it

**Closed** 2022-11-04 02:22 UTC
Labels: enhancement, Needs implementation on AWS provider
